### PR TITLE
Added demo code for animatedProperty and setBorder

### PR DESCRIPTION
**Pull request by FDelporte**

### CODE REVIEW

**Comment by FDelporte** [comment]
@JonathanGiles  hello, did this project stop?

**Comment by JonathanGiles** [comment]
Nope, definitely not. Just got distracted - sorry :-)

**Comment by JonathanGiles** [comment]
Thanks, and sorry for the delay!

**Comment by FDelporte** [comment]
@JonathanGiles other components need to be extended?

**Comment by JonathanGiles** [comment]
Not at this point, thanks!

**Pull request merged**
