### PR TITLE
Initial experiments of adding demo usage to the ProgressIndicatorDemo

### PR DESCRIPTION
**Pull request by FDelporte**
Is this the kind of demos you expect? I'm just having some issue to get it "full screen size", seems holder.prefWidthProperty().bind(container.prefWidthProperty()); is not the correct way to achieve this...

### CODE REVIEW

**Comment by JonathanGiles** [comment]
Looks fine. I can finalise it if you want - otherwise keep going and let me know when to review :-)

**Comment by FDelporte** [comment]
Can you finalise please so I can see how you solve the full size problem. This is the most anyoing problem I always face with JavaFX. Can you add a chapter about that in your book? ;-)

Afterwards I'll check which other ProgressIndicator functions I can add with a demo.

**Comment by JonathanGiles** [comment]
I merged and made some improvements. Check them out and improve as desired (although it is probably good enough for now, so we can probably move on to another demo instead).

**Comment by JonathanGiles** [comment]
I did a follow-up push to show how to make the ProgressIndicator massive - it's just setting the max size.

**Pull request merged**
