### PR TITLE
DialogsDemo Update

### PR DESCRIPTION
**Pull request by AlmasB**
- [X] VBox: same width buttons, 5px spacing
- [X] Text in each dialog for demo
- [X] Custom result converter, UsernamePassword
- [X] `showAndWait()`

### CODE REVIEW

**Comment by JonathanGiles** [comment]
Did you want me to merge now or wait? Thanks!

**Comment by AlmasB** [comment]
I'd say keep the PR open for now, I'll let you know when the remaining TODO is done. Cheers

**Comment by AlmasB** [comment]
@JonathanGiles all done, ready for review

**Comment by JonathanGiles** [comment]
Thanks. Very nice. I pushed some minor tweaks. If you have bandwidth, a demo with Spinner would be appreciated (again, HelloSpinner from OpenJFX can help here).

**Pull request merged**
